[build]
  # Build command (if needed for future builds)
  command = "echo 'Static site - no build needed'"

  # Directory to publish
  publish = "src/frontend"

  # Ignore build for static sites
  ignore = "git diff --quiet HEAD^ HEAD -- src/frontend/"

[build.environment]
  # Node version for any future build processes
  NODE_VERSION = "18"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Cache static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirects for SPA functionality
[[redirects]]
  from = "/api/*"
  to = "https://api.returntothesource.org/:splat"
  status = 200

# Custom 404 page
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

# Build hooks (optional)
[build.hooks]
  prebuild = "echo 'Starting deployment...'"
  postbuild = "echo 'Deployment completed successfully'"